# -*- coding: utf-8 -*-
"""txttoimg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pACNNEdBbWaPjyAiOAqaJTqWPKljA1Wq
"""

import json
import nbformat

# Path to the current notebook
notebook_path = '/content/colab_notebook.ipynb'  # This is often not accessible directly

# Workaround: create widget metadata dynamically in Colab
from google.colab import _message

# This tells Colab to initialize widgets correctly
_message.blocking_request('set_notebook_metadata', {
    "metadata": {
        "widgets": {
            "application/vnd.jupyter.widget-state+json": {
                "state": {},
                "version_major": 2,
                "version_minor": 0
            }
        }
    }
})

print("✅ Notebook metadata fixed (Google Colab widget state initialized)")

# Fast Text-to-Image Generator using Hugging Face & Gradio
# Optimized for Speed - Generates images in 5-15 seconds!

# Install required packages
!pip install -q diffusers transformers accelerate gradio

import torch
from diffusers import DiffusionPipeline
import gradio as gr
from PIL import Image
import os

# Set your Hugging Face token here
HF_TOKEN = "replace the hugging face key"  # Replace with your token

# Check if GPU is available
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

# Load the model - Using SDXL-Turbo for ULTRA FAST generation!
print("Loading model... This may take a few minutes...")

# SDXL-Turbo can generate images in just 1-4 steps!
model_id = "stabilityai/sdxl-turbo"

pipe = DiffusionPipeline.from_pretrained(
    model_id,
    torch_dtype=torch.float16 if device == "cuda" else torch.float32,
    use_auth_token=HF_TOKEN,
    variant="fp16" if device == "cuda" else None
)

# Move to GPU if available
pipe = pipe.to(device)

# Enable memory optimization
if device == "cuda":
    pipe.enable_attention_slicing()
    pipe.enable_vae_slicing()

print("Model loaded successfully! Ready for FAST generation!")

# Generate image function
def generate_image(prompt, num_steps, guidance_scale):
    """
    Generate an image from text prompt - FAST VERSION

    Args:
        prompt: Text description of desired image
        num_steps: Number of inference steps (1-4 for turbo model)
        guidance_scale: Should be 0.0 for turbo model
    """
    try:
        with torch.inference_mode():
            image = pipe(
                prompt=prompt,
                num_inference_steps=num_steps,
                guidance_scale=guidance_scale,
                height=512,
                width=512
            ).images[0]

        return image

    except Exception as e:
        return f"Error generating image: {str(e)}"

# Example prompts for quick testing
example_prompts = [
    "a cat wearing sunglasses on a beach",
    "futuristic city at night with neon lights",
    "a magical forest with glowing mushrooms",
    "a steaming cup of coffee on a wooden table",
    "astronaut riding a horse on mars"
]

# Create Gradio interface
with gr.Blocks(title="⚡ Fast Text-to-Image Generator") as demo:
    gr.Markdown(
        """
        # ⚡ Ultra-Fast Text-to-Image Generator
        Generate images in **5-15 seconds** using SDXL-Turbo!
        Perfect for low-end systems and quick iterations.
        """
    )

    with gr.Row():
        with gr.Column():
            prompt_input = gr.Textbox(
                label="Prompt",
                placeholder="Describe the image you want to create...",
                lines=3,
                value="a beautiful landscape with mountains and a lake, sunset"
            )

            steps_slider = gr.Slider(
                minimum=1,
                maximum=4,
                value=2,
                step=1,
                label="Steps (1-4, lower = faster)",
                info="SDXL-Turbo works best with 1-4 steps!"
            )

            guidance_slider = gr.Slider(
                minimum=0.0,
                maximum=1.0,
                value=0.0,
                step=0.1,
                label="Guidance Scale",
                info="Keep at 0.0 for turbo model"
            )

            generate_btn = gr.Button("🚀 Generate Image", variant="primary", size="lg")

            gr.Examples(
                examples=example_prompts,
                inputs=prompt_input,
                label="Try these example prompts:"
            )

        with gr.Column():
            output_image = gr.Image(label="Generated Image", type="pil")
            generation_info = gr.Textbox(label="Info", value="Ready to generate!")

    gr.Markdown(
        """
        ### ⚡ Why This is So Fast:
        - **SDXL-Turbo**: Specialized for 1-4 step generation (vs 20-50 steps)
        - **No Negative Prompts**: Turbo model doesn't use them
        - **Fixed Resolution**: 512x512 for optimal speed
        - **Direct Generation**: No complex scheduling needed

        ### 💡 Quick Tips:
        - **1-2 steps**: Ultra fast (5-8 seconds), good quality
        - **3-4 steps**: Slightly slower (10-15 seconds), better quality
        - Be descriptive but concise in prompts
        - Works great for concept art, quick mockups, and iterations

        ### 🔧 Alternative Fast Models:
        If this is still slow, try these in the code:
        - `segmind/small-sd` (even smaller, faster)
        - `runwayml/stable-diffusion-v1-5` (classic, moderate speed)
        """
    )

    # Connect the button to the function
    generate_btn.click(
        fn=generate_image,
        inputs=[
            prompt_input,
            steps_slider,
            guidance_slider
        ],
        outputs=output_image
    )

# Launch the interface
print("\n" + "="*50)
print("🚀 Launching Fast Image Generator!")
print("="*50 + "\n")
demo.launch(share=True, debug=True)